name: Parallel Job Resource Conflict

on:
  schedule:
    - cron: '*/13 * * * *'
  workflow_dispatch:

jobs:
  setup-and-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create server script
      run: |
        echo "Creating server script..."
        echo "#!/bin/bash" > server.sh
        echo "echo 'Starting server on port 3000...'" >> server.sh
        echo "nc -l 3000" >> server.sh
        chmod +x server.sh
        
    - name: Create PR
      run: |
        git checkout -b parallel-test-$(date +%s)
        git add .
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Add server script"
        git push origin HEAD
        gh pr create --title "Parallel test PR" --body "Automated parallel test PR" --head $(git branch --show-current)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  server-1:
    needs: setup-and-pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        ./server.sh &

  server-2:
    needs: setup-and-pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        ./server.sh
